// Icon exports - Material Icons from react-icons
// Source: https://react-icons.github.io/react-icons/search/#q=material

// Material Icons (filled)
export {
  // Common icons
  MdHome,
  MdSearch,
  MdMenu,
  MdClose,
  MdArrowBack,
  MdArrowForward,
  MdArrowUpward,
  MdArrowDownward,
  MdAdd,
  MdRemove,
  MdCheck,
  MdCancel,
  MdInfo,
  MdWarning,
  MdError,
  MdCheckCircle,
  MdCancel as MdCancelCircle,
  MdSettings,
  MdPerson,
  MdEmail,
  MdPhone,
  MdLocationOn,
  MdCalendarToday,
  MdAccessTime,
  MdEdit,
  MdDelete,
  MdSave,
  MdDownload,
  MdUpload,
  MdShare,
  MdFavorite,
  MdFavoriteBorder,
  MdStar,
  MdStarBorder,
  MdVisibility,
  MdVisibilityOff,
  MdLock,
  MdLockOpen,
  MdNotifications,
  MdNotificationsNone,
  MdFilterList,
  MdSort,
  MdMoreVert,
  MdMoreHoriz,
  MdRefresh,
  MdAutorenew,
} from 'react-icons/md';

// Material Icons (outlined)
export {
  // Common outlined icons
  MdOutlineHome,
  MdOutlineSearch,
  MdOutlineMenu,
  MdOutlineClose,
  MdOutlineArrowBack,
  MdOutlineArrowForward,
  MdOutlineAdd,
  MdOutlineRemove,
  MdOutlineCheck,
  MdOutlineCancel,
  MdOutlineInfo,
  MdOutlineWarning,
  MdOutlineError,
  MdOutlineSettings,
  MdOutlinePerson,
  MdOutlineEmail,
  MdOutlinePhone,
  MdOutlineLocationOn,
  MdOutlineCalendarToday,
  MdOutlineAccessTime,
  MdOutlineEdit,
  MdOutlineDelete,
  MdOutlineSave,
  MdOutlineDownload,
  MdOutlineUpload,
  MdOutlineShare,
  MdOutlineFavorite,
  MdOutlineFavoriteBorder,
  MdOutlineStar,
  MdOutlineStarBorder,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdOutlineLock,
  MdOutlineLockOpen,
  MdOutlineNotifications,
  MdOutlineNotificationsNone,
  MdOutlineFilterList,
  MdOutlineSort,
  MdOutlineMoreVert,
  MdOutlineMoreHoriz,
  MdOutlineRefresh,
} from 'react-icons/md';

// Material Symbols (newer, more icons)
export {
  // Common Material Symbols
  TbCube,
} from 'react-icons/tb';
